---
title: "Introdução ao R e ao RStudio"
output:
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

The goal of this lab is to introduce you to R and RStudio, which you'll be using
throughout the course both to learn the statistical concepts discussed in the 
texbook and also to analyze real data and come to informed conclusions.  To 
straighten out which is which: R is the name of the programming language itself 
and RStudio is a convenient interface.

## The Data: Dr. Arbuthnot's Baptism Records

The Arbuthnot data set refers to Dr. John Arbuthnot, an 18<sup>th</sup> century 
physician, writer, and mathematician.  He was interested in the ratio of newborn
boys to newborn girls, so he gathered the baptism records for children born in
London for every year from 1629 to 1710.  We can take a look at the data by 
typing its name into the console.


This command will only show the number of boys baptized each year.

1.  What command would you use to extract just the counts of girls baptized? Try
    it!

Notice that the way R has printed these data is different. When we looked at the
complete data frame, we saw 82 rows, one on each line of the display. These data
are no longer structured in a table with other variables, so they are displayed 
one right after another. Objects that print out in this way are called *vectors*;
they represent a set of numbers. R has added numbers in [brackets] along the 
left side of the printout to indicate locations within the vector. For example,
`5218` follows `[1]`, indicating that `5218` is the first entry in the vector. 
And if `[43]` starts a line, then that would mean the first number on that line
would represent the 43<sup>rd</sup> entry in the vector.

Notice that the help file replaces the plot  in the lower right panel. You can 
toggle between plots and help files using the tabs at the top of that panel.

2.  Is there an apparent trend in the number of girls baptized over the years?  
    How would you describe it?

Now, suppose we want to plot the total number of baptisms.  To compute this, we 
could use the fact that R is really just a big calculator. We can type in 
mathematical expressions like

Note that with R as with your calculator, you need to be conscious of the order 
of operations.  Here, we want to divide the number of boys by the total number 
of newborns, so we have to use parentheses.  Without them, R will first do the 
division, then the addition, giving you something that is not a proportion.

3.  Now, make a plot of the proportion of boys over time. What do you see? Tip: 
If you use the up and down arrow keys, you can scroll through your previous 
commands, your so-called command history. You can also access it by clicking on 
the history tab in the upper right panel.  This will save you a lot of typing in
the future.


This seems like a fair bit for your first lab, so let's stop here. To exit 
RStudio you can click the *x* in the upper right corner of the whole window.  
You will be prompted to save your workspace. If you click *save*, RStudio will 
save the history of your commands and all the objects in your workspace so that 
the next time you launch RStudio, you will see `arbuthnot` and you will have 
access to the commands you typed in your previous session. For now, click *save*,
then start up RStudio again.

* * *

## On Your Own

In the previous few pages, you recreated some of the displays and preliminary 
analysis of Arbuthnot's baptism data. Your assignment involves repeating these 
steps, but for present day birth records in the United States.  Load up the 
present day data with the following command.

